apiVersion: v1
kind: Namespace
metadata:
  name: sentineldf

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sentineldf-api-pdb
  namespace: sentineldf
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: sentineldf-api

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sentineldf-api-deny-all
  namespace: sentineldf
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: sentineldf-api
  policyTypes: ["Ingress","Egress"]
  ingress:
    - from:
        - namespaceSelector: {}
  egress:
    - to:
        - namespaceSelector: {}
