name: CD

on:
  workflow_run:
    workflows: [ "CI" ]
    types: [ "completed" ]
    branches: [ "main" ]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sentineldf-api:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${KUBECONFIG_FILE}" | base64 -d > ~/.kube/config
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_B64 }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install sentineldf-api charts/sentineldf-api \
            --namespace sentineldf --create-namespace \
            --set image.repository=ghcr.io/${{ github.repository_owner }}/sentineldf-api \
            --set image.tag=latest
